# Generated by Django 5.1.3 on 2024-11-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
