# Generated by Django 5.1.3 on 2024-11-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='product_image'),
            preserve_default=False,
        ),
    ]
