# Generated by Django 5.1.3 on 2024-11-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
