# Generated by Django 5.1.3 on 2024-11-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orders_payment_method_alter_orders_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping_address',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
