# Generated by Django 5.1.3 on 2024-11-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orders_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='shipping_address',
        ),
    ]
