# Generated by Django 5.1.3 on 2024-11-25 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_useraddress_is_default'),
        ('order', '0004_remove_orders_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping_address',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='authentication.useraddress'),
            preserve_default=False,
        ),
    ]
