# Generated by Django 5.1.3 on 2024-11-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orders_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
