# Generated by Django 5.1.3 on 2024-11-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_otp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otp',
            table='otp',
        ),
    ]
