# Generated by Django 5.1.3 on 2024-11-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
