# Generated by Django 5.1.3 on 2024-11-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_remove_user_date_joined_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='otp',
            table=None,
        ),
    ]
