# Generated by Django 5.1.3 on 2024-11-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_otp_attempts_otp_token_alter_otp_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
