# Generated by Django 5.1.3 on 2024-11-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_useraddress_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
